pomodoro:
  focus_minutes: 25
  break_minutes: 5

drowsiness:
  eyes_closed_seconds_threshold: 5
  frame_skip: 2
  eye_model_path: models/eye_state_cnn.keras

alarm:
  default_video: "https://www.youtube.com/watch?v=QH2-TGUlwu4"
  max_volume: 200

fun_game:
  expression_model_path: models/expression_cnn.keras
